version: "3.8"
services:
  fastapi:
    build: ./src/main/java/com/agriml/python/fastapi
    ports:
      - "8000:8000"

  springboot:
    build: ./springboot
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
