version: "3.8"
services:
  fastapi:
    build: ./src/main/java/com/agriml/python/api
    ports:
      - "8000:8000"

  springboot:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
